;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Knockdown",DevComment="")
+GameplayTagList=(Tag="Ability.Pushback",DevComment="")
+GameplayTagList=(Tag="Ability.Stagger",DevComment="")
+GameplayTagList=(Tag="HitReact.Knockdown",DevComment="")
+GameplayTagList=(Tag="HitReact.Pushback",DevComment="")
+GameplayTagList=(Tag="HitReact.Stagger",DevComment="")
+GameplayTagList=(Tag="Skill.1",DevComment="")
+GameplayTagList=(Tag="Skill.2",DevComment="")
+GameplayTagList=(Tag="Skill.3",DevComment="")
+GameplayTagList=(Tag="Widget.CreditScreen",DevComment="")
+GameplayTagList=(Tag="Widget.StoryScreen",DevComment="")

